openapi: "3.1.0"
info:
  title: "travel_diary_api API"
  description: "travel_diary_api API"
  version: "1.0.0"
servers:
  - url: "https://skills-travel-diary-api.eliaschen.dev"
    description: Deployment
  - url: "http://localhost:8080"
    description: Local
paths:
  /api/{file}:
    get:
      description: ""
      parameters:
        - name: "file"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Missing file"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "File not found"
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "string"
                format: "byte"
            image/jpeg:
              schema:
                type: "string"
                format: "byte"
            application/octet-stream:
              schema:
                type: "string"
                format: "byte"
  /api/diary:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "string"
  /api/diary/collection:
    get:
      description: ""
      parameters:
        - name: "auth_token"
          in: "header"
          required: false
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FavoriteDiaryGetResponse"
              examples:
                Example#1:
                  description: ""
                  value:
                    msg: "Success"
                    data: [ ]
        "403":
          description: "Forbidden"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FavoriteDiaryResponse"
              examples:
                Example#1:
                  description: ""
                  value:
                    msg: "UnAuthorized"
                    data:
                      diaryId: ""
                      favoriteDateTime: ""
    put:
      description: ""
      parameters:
        - name: "auth_token"
          in: "header"
          required: false
          schema:
            type: "string"
        - name: "diary_id"
          in: "query"
          required: false
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FavoriteDiaryResponse"
              examples:
                Example#1:
                  description: ""
                  value:
                    msg: "Success"
                    data:
                      diaryId: ""
                      favoriteDateTime: ""
        "403":
          description: "Forbidden"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FavoriteDiaryResponse"
              examples:
                Example#1:
                  description: ""
                  value:
                    msg: "UnAuthorized"
                    data:
                      diaryId: ""
                      favoriteDateTime: ""
  /api/reset:
    delete:
      description: ""
  /api/user-agreement:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/html:
              schema:
                type: "string"
  /api/users:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Map_String"
  /api/users/signin:
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AuthResponse"
              examples:
                Example#1:
                  description: ""
                  value:
                    data: "null"
                    msg: "Sign in successful"
                Example#2:
                  description: ""
                  value:
                    data: "null"
                    msg: "Sign in successful"
        "401":
          description: "Unauthorized"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AuthResponse"
              examples:
                Example#1:
                  description: ""
                  value:
                    data:
                      authToken: ""
                    msg: "Wrong password"
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AuthResponse"
              examples:
                Example#1:
                  description: ""
                  value:
                    data:
                      authToken: ""
                    msg: "null"
components:
  schemas:
    FavoriteDiaryData:
      type: "object"
      properties:
        diaryId:
          type: "string"
          default: ""
        favoriteDateTime:
          type: "string"
          default: ""
      required:
        - "diaryId"
        - "favoriteDateTime"
    FavoriteDiaryGetResponse:
      type: "object"
      properties:
        msg:
          type: "string"
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/FavoriteDiaryData"
      required:
        - "msg"
        - "data"
    FavoriteDiaryResponse:
      type: "object"
      properties:
        msg:
          type: "string"
        data:
          $ref: "#/components/schemas/FavoriteDiaryData"
      required:
        - "msg"
        - "data"
    Map:
      type: "object"
      properties: { }
    Map_String:
      type: "string"
    AuthRequest:
      type: "object"
      properties:
        userEmailAddress:
          type: "string"
        userPassword:
          type: "string"
      required:
        - "userEmailAddress"
        - "userPassword"
    AuthData:
      type: "object"
      properties:
        authToken:
          type: "string"
      required:
        - "authToken"
    AuthResponse:
      type: "object"
      properties:
        data:
          $ref: "#/components/schemas/AuthData"
        msg:
          type: "string"
      required:
        - "data"
        - "msg"